# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_tbl_mst_newsarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mst_newsarticle',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mst_newsarticle',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mst_newsarticle',
            name='publishedAt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mst_newsarticle',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mst_newsarticle',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_mst_newsarticle',
            name='urlToImage',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
