# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20170609_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_MST_NewsArticle',
            new_name='NewsArticle',
        ),
        migrations.RenameModel(
            old_name='tbl_TRN_NewsBookmark',
            new_name='NewsBookmark',
        ),
        migrations.RenameModel(
            old_name='tbl_TRN_NewsComment',
            new_name='NewsComment',
        ),
        migrations.RenameModel(
            old_name='tbl_TRN_NewsLike',
            new_name='NewsLike',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='articleId',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='publishedAt',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='urlToImage',
            new_name='url_to_image',
        ),
        migrations.RenameField(
            model_name='newsbookmark',
            old_name='bookmarkId',
            new_name='bookmark_id',
        ),
        migrations.RenameField(
            model_name='newsbookmark',
            old_name='bookmarkedAt',
            new_name='bookmarked_at',
        ),
        migrations.RenameField(
            model_name='newscomment',
            old_name='commentId',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='newscomment',
            old_name='commentedAt',
            new_name='commented_at',
        ),
        migrations.RenameField(
            model_name='newslike',
            old_name='likeId',
            new_name='like_id',
        ),
        migrations.AlterField(
            model_name='newsbookmark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.NewsArticle', to_field='article_id'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.NewsArticle', to_field='article_id'),
        ),
        migrations.AlterField(
            model_name='newslike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.NewsArticle', to_field='article_id'),
        ),
    ]
