# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20170613_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url_to_image',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
