# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20170616_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslike',
            name='liked_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
