# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_newslike_liked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslike',
            name='like',
        ),
    ]
