# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_remove_newslike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsbookmark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_bookmark', to='newsapp.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='newsbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='newsapp.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newslike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='newsapp.NewsArticle'),
        ),
        migrations.AlterField(
            model_name='newslike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='newscomment',
            unique_together=set([]),
        ),
    ]
