# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_TRN_NewsBookmark',
            fields=[
                ('bookmarkId', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarkedAt', models.DateField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.tbl_MST_NewsArticle')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_TRN_NewsComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('commentedAt', models.DateField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.tbl_MST_NewsArticle')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_TRN_NewsLike',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.tbl_MST_NewsArticle')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
