# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_tbl_trn_newsbookmark_tbl_trn_newscomment_tbl_trn_newslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mst_newsarticle',
            name='source',
            field=models.CharField(default='', max_length=30),
        ),
    ]
