# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-02 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_MST_Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=30)),
                ('movie_duration', models.CharField(max_length=7)),
                ('movie_release_date', models.DateField()),
                ('movie_director', models.CharField(max_length=30)),
                ('movie_lead_roles', models.CharField(max_length=300)),
                ('movie_writer', models.CharField(max_length=150)),
                ('movie_banner_link', models.CharField(max_length=200)),
                ('movie_average_rating', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=15)),
                ('movie_storyline', models.CharField(max_length=500)),
                ('movie_certificate', models.CharField(max_length=3)),
                ('movie_language', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_MST_User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_MST_User_Comments',
            fields=[
                ('user_comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_User')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_MST_User_Rating',
            fields=[
                ('user_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_User')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_TRN_Watchlist',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_User')),
            ],
        ),
    ]
