# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-02 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_MST_Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_director', models.CharField(max_length=30)),
                ('movie_writer', models.CharField(max_length=30)),
                ('movie_genre', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='tbl_MST_User_Comments',
            new_name='tbl_TRN_User_Comments',
        ),
        migrations.RenameModel(
            old_name='tbl_MST_User_Rating',
            new_name='tbl_TRN_User_Rating',
        ),
        migrations.RemoveField(
            model_name='tbl_mst_movie',
            name='movie_director',
        ),
        migrations.RemoveField(
            model_name='tbl_mst_movie',
            name='movie_genre',
        ),
        migrations.RemoveField(
            model_name='tbl_mst_movie',
            name='movie_writer',
        ),
        migrations.AddField(
            model_name='tbl_mst_movie',
            name='director_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tbl_MST_Director'),
        ),
    ]
