# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(db_index=True, max_length=1000)),
                ('article_url', models.URLField()),
                ('article_thumbnail', django_thumbs.db.models.ImageWithThumbsField(upload_to='images')),
            ],
        ),
    ]
